export { SliderRow, Section, SubSection } from './SliderRow';
export { DimensionsSection } from './DimensionsSection';
export { VisualsSection } from './VisualsSection';
export { NozzleSection } from './NozzleSection';
export { LiftingLugSection } from './LiftingLugSection';
export { WeldSection } from './WeldSection';
export { SaddleSection } from './SaddleSection';
export { ImageOverlaySection } from './ImageOverlaySection';
export { ScanCompositeSection } from './ScanCompositeSection';
export { AnnotationSection } from './AnnotationSection';
export { CoverageSection } from './CoverageSection';
export { InspectionImageSection } from './InspectionImageSection';
export { ThresholdSection } from './ThresholdSection';
